/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/indexing/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get indexing status */
        get: operations["get_indexing_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ingestion configuration */
        get: operations["get_ingestion_config"];
        put?: never;
        /** Save Ingestion configuration */
        post: operations["save_ingestion_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Process JSON ingestion request.
         * @description Returns 202 Accepted immediately — the body is a job-started envelope, not the
         *     final ingestion result. Clients poll `/ingestion/progress/{progress_id}` for
         *     the actual outcome.
         */
        post: operations["process_json"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get ingestion status */
        get: operations["get_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingestion/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate JSON data without processing */
        post: operations["validate_json"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/llm-query/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a follow-up question about query results */
        post: operations["chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List logs from the in-memory RING buffer.
         * @description Reads are cheap clones from a `RwLock<VecDeque<LogEntry>>` — no I/O,
         *     no async work needed. We still keep the response shape (`{logs, count,
         *     timestamp}`) the dashboard parser expects.
         */
        get: operations["list_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/level": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update feature-specific log level at runtime.
         * @description Translated to the RELOAD handle's `EnvFilter` directive vocabulary:
         *     `{feature, level}` becomes `"{feature_lower}={level_lower},info"`.
         *     Each call replaces the full filter — per-feature levels do not stack
         *     across calls. The dashboard already tracks its own per-feature state
         *     and resends the merged view on each change, so single-call replacement
         *     matches what the UI expects today. Phase 6 will switch the dashboard
         *     to a `{directive}` body so the frontend owns the merge.
         */
        put: operations["update_feature_level"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream logs via Server-Sent Events.
         * @description Each tracing event is fanned out as one JSON `LogEntry` on the WEB
         *     layer's broadcast channel. The handler subscribes per connection,
         *     wraps the receiver in a [`BroadcastStream`], and forwards each frame
         *     as an SSE `data:` line. `RecvError::Lagged` (slow consumer) silently
         *     drops the stale slot — the dashboard recovers by reading future
         *     events; back-pressuring the tracing pipeline would be worse.
         */
        get: operations["stream_logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mutation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute a mutation. */
        post: operations["execute_mutation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/native-index/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the native word index for a term. */
        get: operations["native_index_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Execute a query. */
        post: operations["execute_query"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a schema by name. */
        get: operations["get_schema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/{name}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a schema for queries and mutations */
        post: operations["approve_schema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/{name}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block a schema from queries and mutations */
        post: operations["block_schema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_schemas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schemas/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Load schemas from standard directories into memory as Available */
        post: operations["load_schemas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/security/system-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_system_public_key"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/database-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current database configuration */
        get: operations["get_database_config"];
        put?: never;
        /**
         * Update database configuration
         * @description This endpoint updates the database configuration in the node config file.
         *     The server must be restarted for the changes to take effect.
         */
        post: operations["update_database_config"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/migrate-to-cloud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Migrate data to Exemem Cloud (async background job)
         * @description This endpoint initiates S3 sync setup for the local Sled database:
         *     1. Returns immediately with a job ID for progress tracking
         *     2. The background job snapshots local data and uploads encrypted blobs to S3
         *     3. Progress can be monitored via /api/ingestion/progress/{job_id}
         */
        post: operations["migrate_to_cloud"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the node's public key
         * @description This endpoint returns the node's public key for verification purposes.
         *     The public key is generated automatically when the node is created.
         */
        get: operations["get_node_public_key"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/reset-database": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset the database (async background job)
         * @description This endpoint initiates a database reset as a background job:
         *     1. Returns immediately with a job ID for progress tracking
         *     2. The background job clears all data for the current user
         *     3. Progress can be monitored via /api/ingestion/progress/{job_id}
         *
         *     This is a destructive operation that cannot be undone.
         *
         *     # Multi-Tenancy Support
         *
         *     This endpoint respects multi-tenancy by only clearing data for the
         *     current user (identified via x-user-hash header). Only the current
         *     user's Sled trees are cleared; other users on the same node are
         *     unaffected.
         */
        post: operations["reset_database"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get system status information */
        get: operations["get_system_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Specifies the AI provider to use for ingestion.
         * @enum {string}
         */
        AIProvider: "Anthropic" | "Ollama";
        /** @description Response for async admin jobs (reset, migration, etc.) */
        AdminJobResponse: {
            job_id?: string | null;
            message: string;
            success: boolean;
        };
        /** @description Configuration for the Anthropic AI provider. */
        AnthropicConfig: {
            api_key: string;
            base_url: string;
            model: string;
        };
        /** @description An atom reference with per-key write timestamp for merge resolution. */
        AtomEntry: {
            atom_uuid: string;
            provenance?: Omit<components["schemas"]["Provenance"], "kind"> | null;
            /** @description Base64-encoded Ed25519 signature over canonical bytes. */
            signature?: string;
            /**
             * Format: int32
             * @description Signature scheme version (1 = hand-rolled canonical concat).
             */
            signature_version?: number;
            /** @description Base64-encoded public key of the writer who signed this entry. */
            writer_pubkey?: string;
            /** Format: int64 */
            written_at?: number;
        };
        /** @description Request for follow-up question */
        ChatRequest: {
            question: string;
            session_id: string;
        };
        /** @description Response to follow-up question */
        ChatResponse: {
            answer: string;
            context_used: boolean;
        };
        CloudSyncConfigDto: {
            api_url: string;
        };
        DatabaseConfigDto: {
            cloud_sync?: components["schemas"]["CloudSyncConfigDto"] | null;
            path: string;
        };
        /** @description Database configuration request/response types */
        DatabaseConfigRequest: {
            database: components["schemas"]["DatabaseConfigDto"];
        };
        DatabaseConfigResponse: {
            message: string;
            requires_restart: boolean;
            success: boolean;
        };
        IndexResult: {
            field: string;
            key_value: components["schemas"]["KeyValue"];
            metadata?: unknown;
            molecule_versions?: number[] | null;
            schema_display_name?: string | null;
            schema_name: string;
            value: unknown;
        };
        /** @enum {string} */
        IndexingState: "Idle" | "Indexing";
        IndexingStatus: {
            /**
             * Format: double
             * @description Average processing time per operation (milliseconds)
             */
            avg_processing_time_ms: number;
            /** @description Current batch being processed (if any) */
            current_batch_size?: number | null;
            /**
             * Format: int64
             * @description Timestamp when current batch started (Unix timestamp in seconds)
             */
            current_batch_start_time?: number | null;
            /**
             * Format: int64
             * @description Timestamp of last indexing operation (Unix timestamp in seconds)
             */
            last_operation_time?: number | null;
            /** @description Number of operations currently being processed */
            operations_in_progress: number;
            /**
             * Format: double
             * @description Current throughput in operations per second
             */
            operations_per_second: number;
            /** @description Total operations queued (waiting to be processed) */
            operations_queued: number;
            state: components["schemas"]["IndexingState"];
            /**
             * Format: int64
             * @description Total operations processed since startup
             */
            total_operations_processed: number;
        };
        /** @description Configuration for the ingestion module. */
        IngestionConfig: {
            anthropic?: components["schemas"]["AnthropicConfig"];
            auto_execute_mutations: boolean;
            enabled: boolean;
            /** Format: int32 */
            max_retries: number;
            ollama: components["schemas"]["OllamaConfig"];
            /**
             * @description Per-role provider / model / sampling overrides. Keyed by [`Role`].
             *     When a role has no entry, [`IngestionConfig::resolve`] falls through
             *     to role defaults + global config.
             */
            overrides?: {
                [key: string]: components["schemas"]["UseCaseOverride"];
            };
            provider: components["schemas"]["AIProvider"];
            /** Format: int64 */
            timeout_seconds: number;
            vision_backend?: components["schemas"]["VisionBackend"];
        };
        /**
         * @description Request for processing JSON ingestion.
         *
         *     This is the canonical request type used by both the HTTP server and Lambda handlers.
         *     Fields use serde defaults so callers can omit optional parameters.
         */
        IngestionRequest: {
            /** @description Whether to auto-execute mutations after generation */
            auto_execute?: boolean;
            /** @description JSON data to ingest */
            data: unknown;
            /** @description SHA256 hash of the original source file content (hex string) */
            file_hash?: string | null;
            /** @description Descriptive name from image vision model (schema metadata, not record data) */
            image_descriptive_name?: string | null;
            /**
             * @description Optional org hash — if set, data is ingested into this org's namespace.
             *     The schema is loaded from the schema service as normal, then org_hash is
             *     applied locally so mutations get org-prefixed storage keys.
             */
            org_hash?: string | null;
            /** @description Progress tracking ID (optional, generated if not provided) */
            progress_id?: string | null;
            /** @description Public key for the operation */
            pub_key?: string;
            /** @description Original source filename (for file uploads) */
            source_file_name?: string | null;
            /** @description Source folder path (set when ingested via smart folder or batch) */
            source_folder?: string | null;
        };
        /** @description Response from the ingestion process */
        IngestionResponse: {
            /** @description Any errors that occurred during processing */
            errors: string[];
            /** @description Number of mutations successfully executed */
            mutations_executed: number;
            /** @description Number of mutations generated */
            mutations_generated: number;
            /** @description Whether a new schema was created */
            new_schema_created: boolean;
            /** @description Progress ID for tracking the ingestion process */
            progress_id?: string | null;
            /** @description Name of the schema used (existing or newly created) */
            schema_used?: string | null;
            /** @description All schemas and keys written during this ingestion */
            schemas_written: components["schemas"]["SchemaWriteRecord"][];
            /** @description Whether the ingestion was successful */
            success: boolean;
        };
        /** @description Status information for the ingestion service */
        IngestionStatus: {
            /** @description Whether mutations are auto-executed by default */
            auto_execute_mutations: boolean;
            /** @description Whether ingestion is properly configured and ready */
            configured: boolean;
            /** @description Whether ingestion is enabled */
            enabled: boolean;
            /** @description Model name being used */
            model: string;
            /** @description AI provider being used (Anthropic or Ollama) */
            provider: string;
        };
        KeyConfig: {
            hash_field?: string | null;
            range_field?: string | null;
        };
        /**
         * @description Write-time metadata stored per-key on the molecule.
         *     Survives atom deduplication because it lives on the key-to-atom
         *     association, not on the content-addressed atom itself.
         */
        KeyMetadata: {
            metadata?: {
                [key: string]: string;
            } | null;
            source_file_name?: string | null;
        };
        /** @description Represents resolved key values for hash and range components. */
        KeyValue: {
            hash?: string | null;
            range?: string | null;
        };
        LogLevelUpdate: {
            feature: string;
            level: string;
        };
        /** @description Request body for migrating to cloud */
        MigrateToCloudRequest: {
            api_key: string;
            api_url: string;
        };
        /** @description A reference to a single atom version. */
        Molecule: {
            /**
             * @description The current atom entry with write timestamp.
             *     Kept as a flattened pair for backward-compat: old data without
             *     `written_at` will deserialize with `written_at: 0` via serde default.
             */
            atom_uuid: string;
            key_metadata?: components["schemas"]["KeyMetadata"] | null;
            molecule_uuid: string;
            provenance?: Omit<components["schemas"]["Provenance"], "kind"> | null;
            /** @description Base64-encoded Ed25519 signature over canonical bytes. */
            signature?: string;
            /**
             * Format: int32
             * @description Signature scheme version (1 = hand-rolled canonical concat).
             */
            signature_version?: number;
            /** Format: date-time */
            updated_at: string;
            /** Format: int64 */
            version?: number;
            /** @description Base64-encoded public key of the writer who last signed this molecule. */
            writer_pubkey?: string;
            /** Format: int64 */
            written_at?: number;
        };
        /**
         * @description A hash-based collection of atom references stored in a HashMap.
         *     Used for collections keyed by a single hash key (no ordering needed).
         */
        MoleculeHash: {
            atom_uuids: {
                [key: string]: components["schemas"]["AtomEntry"];
            };
            key_metadata?: {
                [key: string]: components["schemas"]["KeyMetadata"];
            };
            /** Format: date-time */
            updated_at: string;
            uuid: string;
            /** Format: int64 */
            version?: number;
        };
        /**
         * @description A hash-range-based collection of atom references stored in a nested HashMap<BTreeMap> structure.
         *
         *     This molecule type supports complex indexing where atoms are organized by:
         *     - Hash field: Groups related atoms together
         *     - Range field: Provides ordered access within each hash group
         *
         *     Structure: HashMap<hash_value, BTreeMap<range_value, AtomEntry>>
         */
        MoleculeHashRange: {
            /**
             * @description Atom entries organized by hash and range values
             *     Structure: HashMap<hash_value, BTreeMap<range_value, AtomEntry>>
             */
            atom_uuids: {
                [key: string]: {
                    [key: string]: components["schemas"]["AtomEntry"];
                };
            };
            /**
             * @description Per-key metadata organized by hash and range values
             *     Structure: HashMap<hash_value, BTreeMap<range_value, KeyMetadata>>
             */
            key_metadata?: {
                [key: string]: {
                    [key: string]: components["schemas"]["KeyMetadata"];
                };
            };
            /** @description Order in which atoms were added (for deterministic sampling) */
            update_order?: components["schemas"]["KeyValue"][];
            /**
             * Format: date-time
             * @description Timestamp when this molecule was last updated
             */
            updated_at: string;
            /** @description Unique identifier for this molecule */
            uuid: string;
            /**
             * Format: int64
             * @description Monotonic version counter, bumped on each actual change
             */
            version?: number;
        };
        /** @description A range-based collection of atom references stored in a BTreeMap. */
        MoleculeRange: {
            atom_uuids: {
                [key: string]: components["schemas"]["AtomEntry"];
            };
            key_metadata?: {
                [key: string]: components["schemas"]["KeyMetadata"];
            };
            /** Format: date-time */
            updated_at: string;
            uuid: string;
            /** Format: int64 */
            version?: number;
        };
        /**
         * @description Canonical reference to a single atom version on a single molecule.
         *
         *     Used as a Merkle leaf for `Provenance::Derived::sources_merkle_root` and
         *     as the payload for the forward/reverse lineage indexes (PR 6). The
         *     `written_at` pins recomputation to the exact source version even if the
         *     molecule has moved on.
         */
        MoleculeRef: {
            atom_uuid: string;
            /** @description `None` for single-keyed molecules, `Some(k)` for range-keyed molecules. */
            key?: string | null;
            molecule_uuid: string;
            /**
             * Format: int64
             * @description Nanoseconds since the Unix epoch at which this atom was written.
             */
            written_at: number;
        };
        MutationResponse: {
            mutation_id: string;
        };
        NodeKeyResponse: {
            message: string;
            public_key: string;
            success: boolean;
        };
        /** @description Configuration for the Ollama AI provider. */
        OllamaConfig: {
            base_url: string;
            generation_params?: components["schemas"]["OllamaGenerationParams"];
            model: string;
            /** @description OCR model for text extraction from scanned documents (used by file_to_markdown). */
            ocr_model?: string;
            /** @description Vision model for image captioning/classification (used by file_to_markdown). */
            vision_model?: string;
        };
        /** @description Generation parameters for Ollama models. */
        OllamaGenerationParams: {
            /**
             * Format: float
             * @description Min-p sampling threshold (0.0..=1.0).
             */
            min_p: number;
            /**
             * Format: int32
             * @description Context window size in tokens (2048..=250000).
             */
            num_ctx: number;
            /**
             * Format: int32
             * @description Maximum tokens to generate (2048..=32000).
             */
            num_predict: number;
            /**
             * Format: float
             * @description Presence penalty (0.0..=2.0).
             */
            presence_penalty: number;
            /**
             * Format: float
             * @description Repeat penalty (0.0..=2.0).
             */
            repeat_penalty: number;
            /**
             * Format: float
             * @description Sampling temperature (0.0..=2.0).
             */
            temperature: number;
            /**
             * Format: int32
             * @description Top-k sampling (0 = disabled).
             */
            top_k: number;
            /**
             * Format: float
             * @description Top-p (nucleus) sampling (0.0..=1.0).
             */
            top_p: number;
        };
        /** @description Response for process_json (immediate response). */
        ProcessJsonResponse: {
            message: string;
            progress_id: string;
            success: boolean;
        };
        /**
         * @description Writer identity and verifiability information for a molecule.
         *
         *     `User` — signed by an end-user's keypair; authority is by signature.
         *     `Derived` — produced by a deterministic WASM transform; unsigned.
         *     Authority is by recomputation: given `wasm_hash` + `input_snapshot_hash`,
         *     any node can re-run the transform and check the output matches.
         */
        Provenance: {
            /** @enum {string} */
            kind: "user";
            /** @description Base64-encoded Ed25519 public key of the signer. */
            pubkey: string;
            /** @description Base64-encoded Ed25519 signature over canonical bytes. */
            signature: string;
            /**
             * Format: int32
             * @description Signature scheme version (1 = hand-rolled canonical concat,
             *     matching `Molecule::build_canonical_bytes`).
             */
            signature_version: number;
        } | {
            /**
             * Format: int32
             * @description Canonicalization version for `input_snapshot_hash` and the Merkle
             *     leaves. Starts at 1. Bump if and only if the canonical byte layout
             *     changes — a change here changes the content address, so treat as
             *     forever.
             */
            encoding_version: number;
            /**
             * @description SHA-256 hex of the canonical input snapshot fed to WASM. This is
             *     the content address of the transform inputs.
             */
            input_snapshot_hash: string;
            /** @enum {string} */
            kind: "derived";
            /**
             * @description SHA-256 hex of the Merkle root over the source `MoleculeRef`s.
             *     The full source set lives in local rebuildable indexes (PR 6),
             *     not on the molecule.
             */
            sources_merkle_root: string;
            /** @description SHA-256 hex of the WASM module bytes that produced this molecule. */
            wasm_hash: string;
        };
        /** @description The plan for executing a query */
        QueryPlan: {
            /**
             * @description fold_db's `Query` type lacks `utoipa::ToSchema` upstream, so we
             *     surface it as opaque JSON in the OpenAPI spec. Once Phase 3 of
             *     gbrain projects/api-typegen-unification lands ToSchema for fold_db
             *     types, drop the `value_type` override and let utoipa derive the
             *     real shape.
             */
            query: unknown;
            reasoning: string;
        };
        /** @description Request body for database reset */
        ResetDatabaseRequest: {
            confirm: boolean;
        };
        /**
         * @description Named AI use cases inside fold_db_node.
         * @enum {string}
         */
        Role: "IngestionText" | "Vision" | "Ocr" | "SmartFolder" | "DiscoveryInterests" | "MutationAgent" | "QueryChat";
        /** @description Request to run a query (single-step analyze and execute) */
        RunQueryRequest: {
            query: string;
            session_id?: string | null;
        };
        /**
         * @description Provider/model settings persisted to disk by the UI.
         *     Runtime fields (enabled, retries, timeout) are controlled via env vars only.
         *
         *     # Schema migration
         *
         *     Older configs have a top-level `query: UseCaseOverride` field. Newer
         *     configs use `overrides: HashMap<Role, UseCaseOverride>`. Both fields are
         *     read on load — [`Self::normalize`] seeds `overrides[QueryChat]` from the
         *     legacy `query` field when present. During the rollout window, saves emit
         *     BOTH fields (dual-write) so an older binary can still read the user's
         *     QueryChat override if the feature flag gets rolled back. The legacy
         *     `query` field will be dropped two releases after PR 4 ships.
         */
        SavedConfig: {
            anthropic?: components["schemas"]["AnthropicConfig"];
            ollama: components["schemas"]["OllamaConfig"];
            /** @description Per-role overrides. The new canonical shape (2026-04-22+). */
            overrides?: {
                [key: string]: components["schemas"]["UseCaseOverride"];
            };
            provider: components["schemas"]["AIProvider"];
            query?: components["schemas"]["UseCaseOverride"];
            vision_backend?: components["schemas"]["VisionBackend"];
        };
        /** @description A single schema and the keys that were written to it during ingestion. */
        SchemaWriteRecord: {
            keys_written: components["schemas"]["KeyValue"][];
            schema_name: string;
        };
        /**
         * @description Per-role provider/model/sampling override.
         *
         *     When a field is `None`, the role inherits from role defaults or the parent
         *     config. When set, it wins field-by-field. Keyed by [`Role`] in
         *     [`IngestionConfig::overrides`] and [`SavedConfig::overrides`].
         */
        UseCaseOverride: {
            /**
             * @description Anthropic model override. `None` = inherit from role default or
             *     parent's `anthropic.model`.
             */
            anthropic_model?: string | null;
            generation_params?: components["schemas"]["OllamaGenerationParams"] | null;
            /**
             * @description Ollama model override. `None` = inherit from role default or
             *     parent's `ollama.model` / `vision_model` / `ocr_model`.
             */
            ollama_model?: string | null;
            provider?: components["schemas"]["AIProvider"] | null;
        };
        /**
         * @description Specifies the backend used to convert images → markdown (vision / OCR).
         *     Separate from `AIProvider` (text backend): vision historically only
         *     supported Ollama via `file_to_markdown`, with Anthropic vision added for
         *     environments without a local Ollama daemon (CI, fresh installs).
         * @enum {string}
         */
        VisionBackend: "Ollama" | "Anthropic";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_indexing_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current indexing status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexingStatus"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_ingestion_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingestion config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionConfig"];
                };
            };
        };
    };
    save_ingestion_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SavedConfig"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    process_json: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IngestionRequest"];
            };
        };
        responses: {
            /** @description Ingestion job started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessJsonResponse"];
                };
            };
        };
    };
    get_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingestion status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionStatus"];
                };
            };
        };
    };
    validate_json: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Validation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Answer to question */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Session not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_logs: {
        parameters: {
            query?: {
                /** @description Filter to entries with timestamp >= this value (ms since epoch) */
                since?: number | null;
                /** @description Cap result count (default 1000) */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    update_feature_level: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogLevelUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Reload handle unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stream_logs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream logs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    execute_mutation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Mutation accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    native_index_search: {
        parameters: {
            query: {
                /** @description Search term for native word index */
                term: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of native index results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    execute_query: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": unknown;
            };
        };
        responses: {
            /** @description Array of query result records */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_schema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schema name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schema */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Schema not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approve_schema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schema name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Schema approved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    block_schema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Schema name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_schemas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of schemas with states */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    load_schemas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Load counts for available and data schemas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_system_public_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_database_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database configuration */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseConfigDto"];
                };
            };
        };
    };
    update_database_config: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatabaseConfigRequest"];
            };
        };
        responses: {
            /** @description Configuration updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseConfigResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseConfigResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseConfigResponse"];
                };
            };
        };
    };
    migrate_to_cloud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MigrateToCloudRequest"];
            };
        };
        responses: {
            /** @description Migration job started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobResponse"];
                };
            };
        };
    };
    get_node_public_key: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node public key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeKeyResponse"];
                };
            };
        };
    };
    reset_database: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetDatabaseRequest"];
            };
        };
        responses: {
            /** @description Database reset job started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobResponse"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobResponse"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminJobResponse"];
                };
            };
        };
    };
    get_system_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
