// AUTO-GENERATED by scripts/generate-endpoints.js from http://localhost:9001/api/openapi.json
// Do not edit manually. Run: npm run generate:endpoints

import type { paths } from "../types/openapi";

type PathParams<
  P extends keyof paths,
  M extends keyof paths[P],
> = paths[P][M] extends { parameters: { path: infer T } }
  ? T
  : Record<string, string>;

export const API_ENDPOINTS_DERIVED = {
  GET_INDEXING_STATUS: "/indexing/status",
  GET_INGESTION_CONFIG: "/ingestion/config",
  HEALTH_CHECK: "/ingestion/health",
  PROCESS_JSON: "/ingestion/process",
  GET_STATUS: "/ingestion/status",
  VALIDATE_JSON: "/ingestion/validate",
  ANALYZE_QUERY: "/llm-query/analyze",
  CHAT: "/llm-query/chat",
  EXECUTE_QUERY_PLAN: "/llm-query/execute",
  LIST_LOGS: "/logs",
  GET_CONFIG: "/logs/config",
  RELOAD_CONFIG: "/logs/config/reload",
  GET_FEATURES: "/logs/features",
  UPDATE_FEATURE_LEVEL: "/logs/level",
  STREAM_LOGS: "/logs/stream",
  EXECUTE_MUTATION: "/mutation",
  NATIVE_INDEX_SEARCH: "/native-index/search",
  EXECUTE_QUERY: "/query",
  GET_SCHEMA: (name: PathParams<"/api/schema/{name}", "get">["name"]) =>
    `/schema/${name}`,
  APPROVE_SCHEMA: (
    name: PathParams<"/api/schema/{name}/approve", "post">["name"],
  ) => `/schema/${name}/approve`,
  BLOCK_SCHEMA: (
    name: PathParams<"/api/schema/{name}/block", "post">["name"],
  ) => `/schema/${name}/block`,
  LIST_SCHEMAS: "/schemas",
  LOAD_SCHEMAS: "/schemas/load",
  GET_SYSTEM_PUBLIC_KEY: "/security/system-key",
  GET_DATABASE_CONFIG: "/system/database-config",
  GET_NODE_PRIVATE_KEY: "/system/private-key",
  GET_NODE_PUBLIC_KEY: "/system/public-key",
  RESET_DATABASE: "/system/reset-database",
  RESET_SCHEMA_SERVICE: "/system/reset-schema-service",
  APPLY_SETUP: "/system/setup",
  GET_SYSTEM_STATUS: "/system/status",
  GET_EMBEDDING_CONFIG: "/system/embedding-config",
  UPDATE_EMBEDDING_CONFIG: "/system/embedding-config",
  GET_DATABASE_STATUS: "/system/database-status",
} as const;

// Base URL prefixes derived from OpenAPI paths
export const API_BASE_URLS = {
  ROOT: "/api",
  INDEXING: "/api/indexing",
  INGESTION: "/api/ingestion",
  LLM_QUERY: "/api/llm-query",
  LOGS: "/api/logs",
  MUTATION: "/api/mutation",
  NATIVE_INDEX: "/api/native-index",
  QUERY: "/api/query",
  SCHEMA: "/api/schema",
  SCHEMAS: "/api/schemas",
  SECURITY: "/api/security",
  SYSTEM: "/api/system",
} as const;

// Endpoints not yet in OpenAPI spec but used by the backend
const API_ENDPOINTS_MANUAL = {
  ANALYZE_FOLLOWUP: "/llm-query/analyze-followup",
  AGENT_QUERY: "/llm-query/agent",
  AUTO_IDENTITY: "/system/auto-identity",
  UPDATE_DATABASE_CONFIG: "/system/database-config",
  GET_DATABASE_STATUS: "/system/database-status",
  INGESTION_UPLOAD: "/ingestion/upload",
  GET_MOLECULE_HISTORY: (uuid: string) => `/history/${uuid}`,
  GET_ATOM_CONTENT: (uuid: string) => `/atom/${uuid}`,
  MIGRATE_TO_CLOUD: "/system/migrate-to-cloud",
} as const;

// Export merged endpoints (generated + manual)
export const API_ENDPOINTS = {
  ...API_ENDPOINTS_DERIVED,
  ...API_ENDPOINTS_MANUAL,
};
export type ApiEndpoint = (typeof API_ENDPOINTS)[keyof typeof API_ENDPOINTS];
